In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [6]:
df=pd.read_csv('digit_train.csv')

In [7]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [8]:
df.shape

(42000, 785)

In [12]:
from  sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.33, random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [17]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [18]:
clf1.fit(X_train,y_train)

C:\Users\MODASUD\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
ay_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [29]:
from sklearn.metrics import confusion_matrix

In [22]:
print("Accurracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accurracy of Decision Tree",accuracy_score(y_test,y_pred2))

Accurracy of Logistic Regression 0.9151515151515152
Accurracy of Decision Tree 0.845021645021645


In [30]:
print("Logistic Regerssion Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1).columns=list(range(0,10)))

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (1607497854.py, line 2)

In [9]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [ ]:
precision_score()

In [31]:
print(confusion_matrix(y_test,y_pred1))

[[1281    0    9    2    5   14   14    2    5    1]
 [   0 1472    9    7    1    5    2    3   19    2]
 [   9   14 1266   26   19   15   19   13   28    5]
 [   5    5   37 1296    1   54    3   17   38   15]
 [   5    3    7    2 1263    3   14    4    7   50]
 [  17    2   11   53   14 1034   20    4   37   13]
 [  17    4   10    4   13   18 1321    2    7    1]
 [   3    3   20   15   16    2    0 1366    8   47]
 [   6   25   16   37    7   42   10    3 1174   14]
 [  14    5    6   16   33   11    0   42   10 1211]]


In [32]:
print(confusion_matrix(y_test,y_pred2))

[[1218    4   17    8    7   21   22   11   14   11]
 [   4 1431   14   14   11   10    7    4   21    4]
 [  13   21 1160   56   21   25   19   42   40   17]
 [  14   20   68 1138   13   82    6   30   54   46]
 [   5   16   14   13 1172   19   18   16   21   64]
 [  17   15   16   82   23  935   37   14   45   21]
 [  11    6   24   14   32   38 1228    5   30    9]
 [  11   13   54   25   13   17    3 1292    7   45]
 [  14   26   42   57   30   37   23   14 1045   46]
 [  10    8   13   32   78   28   10   41   35 1093]]


In [33]:
pd.DataFrame(confusion_matrix(y_test,y_pred1))

0     1     2     3     4     5     6     7     8     9
0  1281     0     9     2     5    14    14     2     5     1
1     0  1472     9     7     1     5     2     3    19     2
2     9    14  1266    26    19    15    19    13    28     5
3     5     5    37  1296     1    54     3    17    38    15
4     5     3     7     2  1263     3    14     4     7    50
5    17     2    11    53    14  1034    20     4    37    13
6    17     4    10     4    13    18  1321     2     7     1
7     3     3    20    15    16     2     0  1366     8    47
8     6    25    16    37     7    42    10     3  1174    14
9    14     5     6    16    33    11     0    42    10  1211

In [34]:
pd.DataFrame(confusion_matrix(y_test,y_pred2))

0     1     2     3     4    5     6     7     8     9
0  1218     4    17     8     7   21    22    11    14    11
1     4  1431    14    14    11   10     7     4    21     4
2    13    21  1160    56    21   25    19    42    40    17
3    14    20    68  1138    13   82     6    30    54    46
4     5    16    14    13  1172   19    18    16    21    64
5    17    15    16    82    23  935    37    14    45    21
6    11     6    24    14    32   38  1228     5    30     9
7    11    13    54    25    13   17     3  1292     7    45
8    14    26    42    57    30   37    23    14  1045    46
9    10     8    13    32    78   28    10    41    35  1093

In [36]:
from  sklearn.metrics import recall_score,precision_score,f1_score

In [37]:
print("For Logistic regression Model")
print('*'*50)
cdf=pd.DataFrame(confusion_matrix(y_test,y_pred1))
print(cdf)
print('*'*50)
print("Precision",precision_score(y_test,y_pred1))
print("Recall-",recall_score(y_test,y_pred1))
print("F1 score-",f1_score(y_test,y_pred1))


For Logistic regression Model
**************************************************
      0     1     2     3     4     5     6     7     8     9
0  1281     0     9     2     5    14    14     2     5     1
1     0  1472     9     7     1     5     2     3    19     2
2     9    14  1266    26    19    15    19    13    28     5
3     5     5    37  1296     1    54     3    17    38    15
4     5     3     7     2  1263     3    14     4     7    50
5    17     2    11    53    14  1034    20     4    37    13
6    17     4    10     4    13    18  1321     2     7     1
7     3     3    20    15    16     2     0  1366     8    47
8     6    25    16    37     7    42    10     3  1174    14
9    14     5     6    16    33    11     0    42    10  1211
**************************************************


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [38]:
print("Precision",precision_score(y_test,y_pred1))
print("Recall-",recall_score(y_test,y_pred1))
print("F1 score-",f1_score(y_test,y_pred1))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [39]:
precision_score(y_test,y_pred1,average=None)# for 10 class indivual

array([0.9439941 , 0.96020874, 0.91013659, 0.88888889, 0.92055394,
       0.86310518, 0.94155381, 0.93818681, 0.88072018, 0.89109639])

In [45]:
recall_score(y_test,y_pred1,average=None)

array([0.96099025, 0.96842105, 0.89533239, 0.88103331, 0.93004418,
       0.85809129, 0.94559771, 0.92297297, 0.88005997, 0.89836795])

In [46]:
f1_score(y_test,y_pred1,average=None)

array([0.95241636, 0.96429741, 0.9026738 , 0.88494367, 0.92527473,
       0.86059093, 0.94357143, 0.93051771, 0.88038995, 0.8947174 ])

In [47]:
f1_score(y_test,y_pred1,average='macro')

0.9139393376446128

In [48]:
recall_score(y_test,y_pred1,average='macro')

0.914091107506439

In [44]:
precision_score(y_test,y_pred1,average='macro')# for 10 class indivual

0.9138444638990719

In [51]:
f1_score(y_test,y_pred1,average='weighted')

0.9150667998364285

In [50]:
recall_score(y_test,y_pred1,average='weighted')

0.9151515151515152

In [49]:
precision_score(y_test,y_pred1,average='weighted')

0.9150396772466788

In [52]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1333
           1       0.96      0.97      0.96      1520
           2       0.91      0.90      0.90      1414
           3       0.89      0.88      0.88      1471
           4       0.92      0.93      0.93      1358
           5       0.86      0.86      0.86      1205
           6       0.94      0.95      0.94      1397
           7       0.94      0.92      0.93      1480
           8       0.88      0.88      0.88      1334
           9       0.89      0.90      0.89      1348

    accuracy                           0.92     13860
   macro avg       0.91      0.91      0.91     13860
weighted avg       0.92      0.92      0.92     13860

